---
# tasks file for omnetpp

- name: Install the omnetpp dependencies
  apt:
    name: "{{ dependencies }}"
    state: present
  vars:
    dependencies:
    - bison
    - build-essential
    - default-jre
    - doxygen
    - flex
    - g++
    - gcc
    - graphviz
    - libosgearth-dev
    - libqt5opengl5-dev
    - libwebkitgtk-3.0-0
    - libxml2-dev
    - openscenegraph
    - openscenegraph-plugin-osgearth
    - osgearth
    - perl
    - python
    - python3
    - qt5-default
    - tcl-dev
    - tk-dev
    - zlib1g-dev

- name: Set the omnetpp variables
  set_fact:
    omnetpp_version: "5.6.1"
    omnetpp_path: "/opt/omnetpp"

- name: Create the omnetpp folder
  file:
    path: "{{ omnetpp_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Add omnetpp to the PATH variable
  lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: 'export PATH=$PATH:{{ omnetpp_path }}/bin'

- name: Download omnetpp
  unarchive:
    remote_src: yes
    src: https://github.com/omnetpp/omnetpp/releases/download/omnetpp-{{ omnetpp_version }}/omnetpp-{{ omnetpp_version }}-src-linux.tgz
    dest: "{{ omnetpp_path }}"
    creates: "{{ omnetpp_path }}/README"
    extra_opts:
    - --strip-components=1
  become: no

- name: Configure omnetpp
  command:
    chdir: "{{ omnetpp_path }}"
    cmd: ./configure
    creates: "{{ omnetpp_path }}/.configured"
  become: no

- name: Prevent configure from being re executed
  file:
    path: "{{ omnetpp_path }}/.configured"
    state: touch
  become: no

- name: Make omnetpp
  make:
    chdir: "{{ omnetpp_path }}"
    params:
      NUM_THREADS: "{{ ansible_processor_vcpus }}"
  become: no
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ omnetpp_path }}/bin"

- name: Make omnetpp (install-menu-item)
  make:
    chdir: "{{ omnetpp_path }}"
    target: install-menu-item
  become: no
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ omnetpp_path }}/bin"

- name: Make omnetpp (install-desktop-icon)
  make:
    chdir: "{{ omnetpp_path }}"
    target: install-desktop-icon
  become: no
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ omnetpp_path }}/bin"
