# Default values for operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

configurations:
  targetLabel: crownlabs.polito.it/operator-selector=production
  keycloak:
    url: "https://auth.crownlabs.example.com/"
    realm: crownlabs
    clientId: client-operator
    clientSecret: my-awesome-secret
    rolesClientId: client-api-server
    # compatibilityMode: set to true for compatibility with older Keycloak versions
    compatibilityMode: false
  mydrivePVCsSize: 1Gi
  mydrivePVCsStorageClassName: rook-nfs
  mydrivePVCsNamespace: mydrive-pvcs

  # If true, the reconciliation will wait for the user to be verified in Keycloak before creating resources.
  # If false, resources will be created immediately after the Tenant is created.
  waitUserVerification: true

  maxConcurrentReconciles: 1
  sandboxClusterRole: crownlabs-sandbox
  tenantNamespaceKeepAlive: 168h
  tenant:
    resourcecaps:
      # Maximum number of virtual cpus that can be requested by a tenant. 0 means unlimited.
      cpu: 25
      # Maximum amount of memory that can be requested by a tenant (expressed in GB). 0 means unlimited.
      memory: 50
      # Maximum number of instances that can be created by a tenant. 0 means unlimited.
      instances: 10

image:
  repository: crownlabs/tenant-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deploymentAnnotations:
  reloader.stakater.com/auto: "true"
podAnnotations: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 20000
  runAsGroup: 20000
  privileged: false

resources:
  limits:
    memory: 700Mi
    cpu: 1000m
  requests:
    memory: 700Mi
    cpu: 100m

webhook:
  deployment:
    certsMount: /tmp/k8s-webhook-server/serving-certs/
    webhookBypassGroups: system:masters,system:serviceaccounts,kubernetes:admin
    baseWorkspaces: utilities
  enableMutating: false
  clusterIssuer: self-signed

rbacResourcesName: crownlabs-tenant-operator
