---
# tasks file for docker

- name: Install Docker prerequisites
  apt:
    name: "{{ docker_prerequisites }}"
    state: present
  vars:
    docker_prerequisites:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Install Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present
  vars:
    docker_packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install Docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
    dest: /usr/local/bin/docker-compose
    mode: +x
  vars:
    compose_version: 1.24.1

- name: Add the local user to the docker group
  user:
    name: "{{ username }}"
    append: yes
    groups: docker
