apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "on"
  generation: 1
  name: crowncloud
  namespace: nextcloud
spec:
  rules:
  - host: crownlabs.polito.it
    http:
      paths:
      - backend:
          serviceName: nextcloud
          servicePort: 80
        path: /cloud(/|$)(.*)
  tls:
  - hosts:
    - crownlabs.polito.it
    secretName: crownlabs-ingress-secret
