apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bastion-operator.fullname" . }}
  labels:
    {{- include "bastion-operator.labels" . | nindent 4 }}
{{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bastion-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "bastion-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bastion-operator.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}-sshd
          securityContext:
            {{- toYaml .Values.securityContexts.bastion | nindent 12 }}
          command: ["/usr/sbin/sshd"]
          args: ["-D", "-e", "-f","/etc/ssh/sshd_config_custom"]
          image: "{{ .Values.image.repositoryBastion }}:{{ include "bastion-operator.version" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ssh-alt
              containerPort: 2222
              protocol: TCP
          volumeMounts:
            - mountPath: /home/bastion/.ssh
              name: authorized-keys
            - mountPath: /host-keys
              name : host-keys
          resources:
            {{- toYaml .Values.resources.bastion | nindent 12 }}
        - name: {{ .Chart.Name }}-operator-sidecar
          securityContext:
            {{- toYaml .Values.securityContexts.operatorSidecar | nindent 12 }}
          image: "{{ .Values.image.repositorySidecar }}:{{ include "bastion-operator.version" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: op-metrics
              containerPort: 8080
              protocol: TCP
            - name: op-probes
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: op-probes
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: op-probes
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: authorized-keys
              mountPath: /auth-keys-vol
          resources:
            {{- toYaml .Values.resources.operatorSidecar | nindent 12 }}
        - name: {{ .Chart.Name }}-tracker-sidecar
          securityContext:
            {{- toYaml .Values.securityContexts.trackerSidecar | nindent 12 }}
          image: "{{ .Values.image.repositoryTrackerSidecar }}:{{ include "bastion-operator.version" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--ssh-tracker-interface={{ .Values.configurations.sshTrackerInterface }}"
            - "--ssh-tracker-port={{ .Values.configurations.sshTrackerPort }}"
            - "--ssh-tracker-snaplen={{ .Values.configurations.sshTrackerSnaplen }}"
            - "--ssh-tracker-metrics-addr={{ .Values.configurations.sshTrackerMetricsAddr }}"
          ports:
            - name: trk-metrics
              containerPort: 8082
              protocol: TCP
            - name: trk-probes
              containerPort: 8083
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: trk-probes
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: trk-probes
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources.trackerSidecar | nindent 12 }}
      volumes:
        - name: authorized-keys
          emptyDir: {}
        - name: host-keys
          secret:
            secretName: {{ .Values.sshKeysSecret.name }}
            defaultMode: 0444
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- include "bastion-operator.selectorLabels" . | nindent 18 }}
              topologyKey: kubernetes.io/hostname

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bastion-operator.fullname" . }}-webssh
  labels:
    {{ include "webssh.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "webssh.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "webssh.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: webssh
          image: "{{ .Values.image.repositoryWebBastion  }}:{{ include "bastion-operator.version" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.webssh.service.targetPort }}
              containerPort: {{ .Values.webssh.config.webSocketPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.webssh.service.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.webssh.service.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - mountPath: /web-keys
              name: web-keys
          resources:
            {{- toYaml .Values.resources.webssh | nindent 12 }}
          args:
            - "--websshuser={{ .Values.webssh.config.user }}"
            - "--websshprivatekeypath=/web-keys/{{ .Values.webssh.masterKey.name }}"
            - "--websshmaxconncount={{ .Values.webssh.config.maxConnCount }}"
            - "--websshvmport={{ .Values.webssh.config.vmPort }}"
            - "--websshwebsocketport={{ .Values.webssh.config.webSocketPort }}"
      volumes:
        - name: web-keys
          secret:
            secretName: {{ .Values.webssh.masterKey.secretName }}
            defaultMode: 0444

