---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: templates.crownlabs.polito.it
spec:
  group: crownlabs.polito.it
  names:
    kind: Template
    listKind: TemplateList
    plural: templates
    shortNames:
    - tmpl
    singular: template
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.prettyName
      name: Pretty Name
      type: string
    - jsonPath: .spec.environmentList[0].mode
      name: Mode
      type: string
    - jsonPath: .spec.environmentList[0].image
      name: Image
      priority: 10
      type: string
    - jsonPath: .spec.environmentList[0].environmentType
      name: Type
      priority: 10
      type: string
    - jsonPath: .spec.environmentList[0].guiEnabled
      name: GUI
      priority: 10
      type: string
    - jsonPath: .spec.environmentList[0].persistent
      name: Persistent
      priority: 10
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha2
    schema:
      openAPIV3Schema:
        description: Template describes the template of a CrownLabs environment to
          be instantiated.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: TemplateSpec is the specification of the desired state of
              the Template.
            properties:
              deleteAfter:
                default: never
                description: |-
                  The maximum lifetime of an Instance referencing the current Template.
                  Once this period is expired, the Instance may be automatically deleted
                  or stopped to save resources. If set to "never", the instance will not be
                  automatically terminated.
                pattern: ^(never|[0-9]+[mhd])$
                type: string
              description:
                description: A textual description of the Template.
                type: string
              environmentList:
                description: The list of environments (i.e. VMs or containers) that
                  compose the Template.
                items:
                  description: Environment defines the characteristics of an environment
                    composing the Template.
                  properties:
                    cluster:
                      description: Cluster
                      properties:
                        clusterNet:
                          description: The network of cluster including pods and services
                          properties:
                            certsan:
                              description: certSAN
                              type: string
                            cni:
                              description: deploy a CNI solution
                              type: string
                            nginxport:
                              description: Nginx Port
                              type: string
                            nginxtargetport:
                              description: Nginx targetPort
                              type: string
                            pods:
                              type: string
                            services:
                              type: string
                          required:
                          - cni
                          - nginxport
                          - nginxtargetport
                          - pods
                          - services
                          type: object
                        controlPlane:
                          description: The controlplane is used to control the cluster
                          properties:
                            provider:
                              description: The controlplane provider
                              type: string
                            replicas:
                              description: The number of controlplane
                              format: int32
                              maximum: 100
                              minimum: 1
                              type: integer
                          required:
                          - provider
                          - replicas
                          type: object
                        machineDeployment:
                          description: The worker deployment rule sepcifying how to
                            bootstrap
                          properties:
                            replicas:
                              description: The number of worker nodes
                              format: int32
                              maximum: 100
                              minimum: 1
                              type: integer
                          required:
                          - replicas
                          type: object
                        name:
                          description: The name identifying the specific cluster.
                          type: string
                        serviceType:
                          enum:
                          - ClusterIP
                          - NodePort
                          - LoadBalancer
                          - ExternalName
                          type: string
                        version:
                          description: The version of kubernetes used in cluster
                          type: string
                      required:
                      - clusterNet
                      - controlPlane
                      - machineDeployment
                      - name
                      - version
                      type: object
                    containerStartupOptions:
                      description: Options to customize container startup
                      properties:
                        contentPath:
                          description: |-
                            Path on which storage (EmptyDir/Storage) will be mounted
                            and into which, if given in SourceArchiveURL, will be extracted the archive
                          type: string
                        enforceWorkdir:
                          default: false
                          description: Whether forcing the container working directory
                            to be the same as the contentPath (or default mydrive
                            path if not specified)
                          type: boolean
                        sourceArchiveURL:
                          description: URL from which GET the archive to be extracted
                            into ContentPath
                          type: string
                        startupArgs:
                          description: Arguments to be passed to the application container
                            on startup
                          items:
                            type: string
                          type: array
                      type: object
                    disableControls:
                      default: false
                      description: For VNC based containers, hide the noVNC control
                        bar when true
                      type: boolean
                    environmentType:
                      description: |-
                        The type of environment to be instantiated, among VirtualMachine,
                        Container, CloudVM and Standalone.
                      enum:
                      - VirtualMachine
                      - Container
                      - CloudVM
                      - Standalone
                      - Cluster
                      type: string
                    guiEnabled:
                      default: true
                      description: Whether the environment is characterized by a graphical
                        desktop or not.
                      type: boolean
                    image:
                      description: The VM or container to be started when instantiating
                        the environment.
                      type: string
                    mode:
                      default: Standard
                      description: The mode associated with the environment (Standard,
                        Exam, Exercise)
                      enum:
                      - Standard
                      - Exam
                      - Exercise
                      type: string
                    mountMyDriveVolume:
                      default: true
                      description: Whether the instance has to have the user's MyDrive
                        volume
                      type: boolean
                    name:
                      description: The name identifying the specific environment.
                      type: string
                    nodeSelector:
                      additionalProperties:
                        type: string
                      description: |-
                        Labels that are used for the selection of the node.
                        They are given by means of a pointer to check the presence of the field.
                        In case it is present, the labels that are chosen are the ones present on the instance
                      type: object
                    persistent:
                      default: false
                      description: |-
                        Whether the environment should be persistent (i.e. preserved when the
                        corresponding instance is terminated) or not.
                      type: boolean
                    resources:
                      description: The amount of computational resources associated
                        with the environment.
                      properties:
                        cpu:
                          description: |-
                            The maximum number of CPU cores made available to the environment
                            (at least 1 core). This maps to the 'limits' specified
                            for the actual pod representing the environment.
                          format: int32
                          minimum: 1
                          type: integer
                        disk:
                          anyOf:
                          - type: integer
                          - type: string
                          description: |-
                            The size of the persistent disk allocated for the given environment.
                            This field is meaningful only in case of persistent or container-based
                            environments, while it is silently ignored in the other cases.
                            In case of containers, when this field is not specified, an emptyDir will be
                            attached to the pod but this could result in data loss whenever the pod dies.
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        memory:
                          anyOf:
                          - type: integer
                          - type: string
                          description: |-
                            The amount of RAM memory assigned to the given environment. Requests and
                            limits do correspond to avoid OOMKill issues.
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        reservedCPUPercentage:
                          description: |-
                            The percentage of reserved CPU cores, ranging between 1 and 100, with
                            respect to the 'CPU' value. Essentially, this corresponds to the 'requests'
                            specified for the actual pod representing the environment.
                          format: int32
                          maximum: 100
                          minimum: 1
                          type: integer
                      required:
                      - cpu
                      - memory
                      - reservedCPUPercentage
                      type: object
                    rewriteURL:
                      default: false
                      description: Whether the environment needs the URL Rewrite or
                        not.
                      type: boolean
                    sharedVolumeMounts:
                      description: The list of information about Shared Volumes that
                        has to be mounted to the instance.
                      items:
                        description: SharedVolumeMountInfo contains mount information
                          for a Shared Volume.
                        properties:
                          mountPath:
                            description: The path the Shared Volume will be mounted
                              in.
                            type: string
                          readOnly:
                            description: Whether this Shared Volume should be mounted
                              with R/W or R/O permission.
                            type: boolean
                          sharedVolume:
                            description: The reference of the Shared Volume this Mount
                              Info is related to.
                            properties:
                              name:
                                description: The name of the resource to be referenced.
                                type: string
                              namespace:
                                description: |-
                                  The namespace containing the resource to be referenced. It should be left
                                  empty in case of cluster-wide resources.
                                type: string
                            required:
                            - name
                            type: object
                        required:
                        - mountPath
                        - readOnly
                        - sharedVolume
                        type: object
                      type: array
                    storageClassName:
                      description: Name of the storage class to be used for the persistent
                        volume (when needed)
                      type: string
                  required:
                  - environmentType
                  - image
                  - mountMyDriveVolume
                  - name
                  - resources
                  type: object
                type: array
              prettyName:
                description: The human-readable name of the Template.
                type: string
              workspace.crownlabs.polito.it/WorkspaceRef:
                description: The reference to the Workspace this Template belongs
                  to.
                properties:
                  name:
                    description: The name of the resource to be referenced.
                    type: string
                  namespace:
                    description: |-
                      The namespace containing the resource to be referenced. It should be left
                      empty in case of cluster-wide resources.
                    type: string
                required:
                - name
                type: object
            required:
            - description
            - environmentList
            - prettyName
            type: object
          status:
            description: TemplateStatus reflects the most recently observed status
              of the Template.
            properties:
              kubeconfigs:
                items:
                  properties:
                    fileaddress:
                      type: string
                    name:
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
