
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: tenants.crownlabs.polito.it
spec:
  group: crownlabs.polito.it
  names:
    kind: Tenant
    listKind: TenantList
    plural: tenants
    singular: tenant
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.firstName
      name: First Name
      type: string
    - jsonPath: .spec.lastName
      name: Last Name
      type: string
    - jsonPath: .spec.email
      name: Email
      priority: 10
      type: string
    - jsonPath: .status.personalNamespace.name
      name: Namespace
      priority: 10
      type: string
    - jsonPath: .status.ready
      name: Ready
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Tenant describes a user of CrownLabs.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TenantSpec is the specification of the desired state of the
              Tenant.
            properties:
              createSandbox:
                default: false
                description: Whether a sandbox namespace should be created to allow
                  the Tenant play with Kubernetes.
                type: boolean
              email:
                description: The email associated with the Tenant, which will be used
                  to log-in into the system.
                pattern: ^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$
                type: string
              firstName:
                description: The first name of the Tenant.
                type: string
              lastName:
                description: The last name of the Tenant.
                type: string
              publicKeys:
                description: The list of the SSH public keys associated with the Tenant.
                  These will be used to enable to access the remote environments through
                  the SSH protocol.
                items:
                  type: string
                type: array
              workspaces:
                description: The list of the Workspaces the Tenant is subscribed to,
                  along with his/her role in each of them.
                items:
                  description: TenantWorkspaceEntry contains the information regarding
                    one of the Workspaces the Tenant is subscribed to, including his/her
                    role.
                  properties:
                    groupNumber:
                      description: The number of the group the Tenant belongs to.
                        Empty means no group.
                      type: integer
                    role:
                      description: The role of the Tenant in the context of the Workspace.
                      enum:
                      - manager
                      - user
                      type: string
                    workspaceRef:
                      description: The reference to the Workspace resource the Tenant
                        is subscribed to.
                      properties:
                        name:
                          description: The name of the resource to be referenced.
                          type: string
                        namespace:
                          description: The namespace containing the resource to be
                            referenced. It should be left empty in case of cluster-wide
                            resources.
                          type: string
                      required:
                      - name
                      type: object
                  required:
                  - role
                  - workspaceRef
                  type: object
                type: array
            required:
            - email
            - firstName
            - lastName
            type: object
          status:
            description: TenantStatus reflects the most recently observed status of
              the Tenant.
            properties:
              failingWorkspaces:
                description: The list of Workspaces that are throwing errors during
                  subscription. This mainly happens if .spec.Workspaces contains references
                  to Workspaces which do not exist.
                items:
                  type: string
                type: array
              personalNamespace:
                description: The namespace containing all CrownLabs related objects
                  of the Tenant. This is the namespace that groups his/her own Instances,
                  together with all the accessory resources (e.g. RBACs, resource
                  quotas, network policies, ...) created by the tenant-operator.
                properties:
                  created:
                    description: Whether the creation succeeded or not.
                    type: boolean
                  name:
                    description: The name of the considered resource.
                    type: string
                required:
                - created
                type: object
              ready:
                description: Whether all subscriptions and resource creations succeeded
                  or an error occurred. In case of errors, the other status fields
                  provide additional information about which problem occurred.
                type: boolean
              sandboxNamespace:
                description: The namespace that can be freely used by the Tenant to
                  play with Kubernetes. This namespace is created only if the .spec.CreateSandbox
                  flag is true.
                properties:
                  created:
                    description: Whether the creation succeeded or not.
                    type: boolean
                  name:
                    description: The name of the considered resource.
                    type: string
                required:
                - created
                type: object
              subscriptions:
                additionalProperties:
                  description: SubscriptionStatus is an enumeration of the different
                    states that can be assumed by the subscription to a service (e.g.
                    successful or failing).
                  enum:
                  - Ok
                  - Failed
                  type: string
                description: The list of the subscriptions to external services (e.g.
                  Keycloak, Nextcloud, ...), indicating for each one whether it succeeded
                  or an error occurred.
                type: object
            required:
            - failingWorkspaces
            - personalNamespace
            - ready
            - sandboxNamespace
            - subscriptions
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - additionalPrinterColumns:
    - jsonPath: .spec.firstName
      name: First Name
      type: string
    - jsonPath: .spec.lastName
      name: Last Name
      type: string
    - jsonPath: .spec.email
      name: Email
      priority: 10
      type: string
    - jsonPath: .status.personalNamespace.name
      name: Namespace
      priority: 10
      type: string
    - jsonPath: .status.ready
      name: Ready
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha2
    schema:
      openAPIV3Schema:
        description: Tenant describes a user of CrownLabs.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TenantSpec is the specification of the desired state of the
              Tenant.
            properties:
              createSandbox:
                default: false
                description: Whether a sandbox namespace should be created to allow
                  the Tenant play with Kubernetes.
                type: boolean
              email:
                description: The email associated with the Tenant, which will be used
                  to log-in into the system.
                pattern: ^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$
                type: string
              firstName:
                description: The first name of the Tenant.
                type: string
              lastName:
                description: The last name of the Tenant.
                type: string
              publicKeys:
                description: The list of the SSH public keys associated with the Tenant.
                  These will be used to enable to access the remote environments through
                  the SSH protocol.
                items:
                  type: string
                type: array
              workspaces:
                description: The list of the Workspaces the Tenant is subscribed to,
                  along with his/her role in each of them.
                items:
                  description: TenantWorkspaceEntry contains the information regarding
                    one of the Workspaces the Tenant is subscribed to, including his/her
                    role.
                  properties:
                    name:
                      description: The Workspace the Tenant is subscribed to.
                      type: string
                    role:
                      description: The role of the Tenant in the context of the Workspace.
                      enum:
                      - manager
                      - user
                      type: string
                  required:
                  - name
                  - role
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - name
                x-kubernetes-list-type: map
            required:
            - email
            - firstName
            - lastName
            type: object
          status:
            description: TenantStatus reflects the most recently observed status of
              the Tenant.
            properties:
              failingWorkspaces:
                description: The list of Workspaces that are throwing errors during
                  subscription. This mainly happens if .spec.Workspaces contains references
                  to Workspaces which do not exist.
                items:
                  type: string
                type: array
              personalNamespace:
                description: The namespace containing all CrownLabs related objects
                  of the Tenant. This is the namespace that groups his/her own Instances,
                  together with all the accessory resources (e.g. RBACs, resource
                  quotas, network policies, ...) created by the tenant-operator.
                properties:
                  created:
                    description: Whether the creation succeeded or not.
                    type: boolean
                  name:
                    description: The name of the considered resource.
                    type: string
                required:
                - created
                type: object
              ready:
                description: Whether all subscriptions and resource creations succeeded
                  or an error occurred. In case of errors, the other status fields
                  provide additional information about which problem occurred.
                type: boolean
              sandboxNamespace:
                description: The namespace that can be freely used by the Tenant to
                  play with Kubernetes. This namespace is created only if the .spec.CreateSandbox
                  flag is true.
                properties:
                  created:
                    description: Whether the creation succeeded or not.
                    type: boolean
                  name:
                    description: The name of the considered resource.
                    type: string
                required:
                - created
                type: object
              subscriptions:
                additionalProperties:
                  description: SubscriptionStatus is an enumeration of the different
                    states that can be assumed by the subscription to a service (e.g.
                    successful or failing).
                  enum:
                  - Ok
                  - Failed
                  type: string
                description: The list of the subscriptions to external services (e.g.
                  Keycloak, Nextcloud, ...), indicating for each one whether it succeeded
                  or an error occurred.
                type: object
            required:
            - failingWorkspaces
            - personalNamespace
            - ready
            - sandboxNamespace
            - subscriptions
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
