---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: workspaces.crownlabs.polito.it
spec:
  group: crownlabs.polito.it
  names:
    kind: Workspace
    listKind: WorkspaceList
    plural: workspaces
    singular: workspace
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.prettyName
      name: Pretty Name
      type: string
    - jsonPath: .status.namespace.name
      name: Namespace
      type: string
    - jsonPath: .status.ready
      name: Ready
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Workspace describes a workspace in CrownLabs.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: WorkspaceSpec is the specification of the desired state of
              the Workspace.
            properties:
              autoEnroll:
                description: AutoEnroll capability definition. If omitted, no autoenroll
                  features will be added.
                enum:
                - ""
                - withApproval
                - immediate
                type: string
              prettyName:
                description: The human-readable name of the Workspace.
                type: string
              quota:
                description: The amount of resources associated with this workspace,
                  and inherited by enrolled tenants.
                properties:
                  cpu:
                    anyOf:
                    - type: integer
                    - type: string
                    description: The maximum amount of CPU required by this Workspace.
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  instances:
                    description: The maximum number of concurrent instances required
                      by this Workspace.
                    format: int32
                    minimum: 1
                    type: integer
                  memory:
                    anyOf:
                    - type: integer
                    - type: string
                    description: The maximum amount of RAM memory required by this
                      Workspace.
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                required:
                - cpu
                - instances
                - memory
                type: object
            required:
            - prettyName
            - quota
            type: object
          status:
            description: WorkspaceStatus reflects the most recently observed status
              of the Workspace.
            properties:
              namespace:
                description: |-
                  The namespace containing all CrownLabs related objects of the Workspace.
                  This is the namespace that groups multiple related templates, together
                  with all the accessory resources (e.g. RBACs) created by the tenant
                  operator.
                properties:
                  created:
                    description: Whether the creation succeeded or not.
                    type: boolean
                  name:
                    description: The name of the considered resource.
                    type: string
                required:
                - created
                type: object
              ready:
                description: |-
                  Whether all subscriptions and resource creations succeeded or an error
                  occurred. In case of errors, the other status fields provide additional
                  information about which problem occurred.
                type: boolean
              subscription:
                additionalProperties:
                  description: |-
                    SubscriptionStatus is an enumeration of the different states that can be
                    assumed by the subscription to a service (e.g. successful or failing).
                  enum:
                  - Ok
                  - Failed
                  type: string
                description: |-
                  The list of the subscriptions to external services (e.g. Keycloak,
                  ...), indicating for each one whether it succeeded or an error
                  occurred.
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
