
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: instances.crownlabs.polito.it
spec:
  group: crownlabs.polito.it
  names:
    kind: Instance
    listKind: InstanceList
    plural: instances
    shortNames:
    - inst
    singular: instance
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.running
      name: Running
      type: string
    - jsonPath: .status.phase
      name: Phase
      type: string
    - jsonPath: .status.url
      name: URL
      priority: 10
      type: string
    - jsonPath: .status.ip
      name: IP Address
      priority: 10
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha2
    schema:
      openAPIV3Schema:
        description: Instance describes the instance of a CrownLabs environment Template.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: InstanceSpec is the specification of the desired state of
              the Instance.
            properties:
              running:
                default: true
                description: Whether the current instance is running or not. This
                  field is meaningful only in case the Instance refers to persistent
                  environments, and it allows to stop the environment (e.g. the underlying
                  VM) without deleting the associated disk. Setting the flag to true
                  will restart the environment, attaching it to the same disk used
                  previously. The flag, on the other hand, is silently ignored in
                  case of non-persistent environments, as the state cannot be preserved
                  among reboots.
                type: boolean
              template.crownlabs.polito.it/TemplateRef:
                description: The reference to the Template to be instantiated.
                properties:
                  name:
                    description: The name of the resource to be referenced.
                    type: string
                  namespace:
                    description: The namespace containing the resource to be referenced.
                      It should be left empty in case of cluster-wide resources.
                    type: string
                required:
                - name
                type: object
              tenant.crownlabs.polito.it/TenantRef:
                description: The reference to the Tenant which owns the Instance object.
                properties:
                  name:
                    description: The name of the resource to be referenced.
                    type: string
                  namespace:
                    description: The namespace containing the resource to be referenced.
                      It should be left empty in case of cluster-wide resources.
                    type: string
                required:
                - name
                type: object
            required:
            - template.crownlabs.polito.it/TemplateRef
            - tenant.crownlabs.polito.it/TenantRef
            type: object
          status:
            description: InstanceStatus reflects the most recently observed status
              of the Instance.
            properties:
              ip:
                description: The internal IP address associated with the remote environment,
                  which can be used to access it through the SSH protocol (leveraging
                  the SSH bastion in case it is not contacted from another CrownLabs
                  Instance).
                type: string
              phase:
                description: The current status Instance, with reference to the associated
                  environment (e.g. VM). This conveys which resource is being created,
                  as well as whether the associated VM is being scheduled, is running
                  or ready to accept incoming connections.
                type: string
              url:
                description: The URL where it is possible to access the remote desktop
                  of the instance (in case of graphical environments)
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
