
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: tenants.crownlabs.polito.it
spec:
  group: crownlabs.polito.it
  names:
    kind: Tenant
    listKind: TenantList
    plural: tenants
    singular: tenant
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.name
      name: Name
      type: string
    - jsonPath: .spec.surname
      name: Surname
      type: string
    - jsonPath: .spec.email
      name: Email
      type: string
    - jsonPath: .spec.ID
      name: ID
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Tenant is the Schema for the tenants API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TenantSpec defines the desired state of Tenant
            properties:
              ID:
                type: string
              createSandbox:
                description: should the resource create the sandbox namespace for k8s practice environment
                type: boolean
              email:
                pattern: ^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$
                type: string
              name:
                type: string
              publicKeys:
                description: public keys of user
                items:
                  type: string
                type: array
              surname:
                type: string
              workspaces:
                description: list of workspaces the user is in
                items:
                  description: UserWorkspaceData contains the info of the workspaces related to a user
                  properties:
                    groupNumber:
                      type: integer
                    role:
                      description: WorkspaceUserRole is an enum for the role of a user in a workspace
                      enum:
                      - Admin
                      - Basic
                      type: string
                    workspaceURL:
                      type: string
                  required:
                  - groupNumber
                  - role
                  - workspaceURL
                  type: object
                type: array
            required:
            - ID
            - email
            - name
            - surname
            type: object
          status:
            description: TenantStatus defines the observed state of Tenant
            properties:
              personalNamespace:
                description: NameCreated contains info about the status of a resource
                properties:
                  created:
                    type: boolean
                  name:
                    type: string
                required:
                - created
                type: object
              sandboxNamespace:
                description: NameCreated contains info about the status of a resource
                properties:
                  created:
                    type: boolean
                  name:
                    type: string
                required:
                - created
                type: object
              subscription:
                additionalProperties:
                  description: SubscriptionStatus is an enum for the status of a subscription to a service
                  enum:
                  - Ok
                  - Failed
                  type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
