apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "operator.webhookname" . }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "operator.webhookname" . }}
webhooks:
- name: validate.instance.crownlabs.polito.it
  failurePolicy: Fail
  admissionReviewVersions:
  - v1
  rules:
  - apiGroups:   ["crownlabs.polito.it"]
    apiVersions: ["v1alpha2"]
    operations:  ["CREATE"]
    resources:   ["instances"]
    scope:       "Namespaced"
  clientConfig:
    service:
      name: {{ include "operator.webhookname" . }}
      namespace: {{ .Release.Namespace }}
      path: /validator-v1alpha2-instance
      port: 443
  sideEffects: None
