apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tenant-operator.fullname" . }}
  labels:
    {{- include "tenant-operator.labels" . | nindent 4 }}
{{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tenant-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "tenant-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tenant-operator.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "tenant-operator.version" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--target-label={{ .Values.configurations.targetLabel }}"
            - "--kc-url={{ .Values.configurations.keycloak.url }}"
            - "--kc-login-realm={{ .Values.configurations.keycloak.loginRealm }}"
            - "--kc-target-realm={{ .Values.configurations.keycloak.targetRealm }}"
            - "--kc-target-client={{ .Values.configurations.keycloak.targetClient }}"
            - "--kc-tenant-operator-user=$(KEYCLOAK_TENANT_OPERATOR_USER)"
            - "--kc-tenant-operator-psw=$(KEYCLOAK_TENANT_OPERATOR_PSW)"
            - "--nc-url={{ .Values.configurations.nextcloud.url }}"
            - "--nc-tenant-operator-user=$(NEXTCLOUD_TENANT_OPERATOR_USER)"
            - "--nc-tenant-operator-psw=$(NEXTCLOUD_TENANT_OPERATOR_PSW)"
            - "--max-concurrent-reconciles={{ .Values.configurations.maxConcurrentReconciles }}"
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: probes
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: probes
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: probes
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: KEYCLOAK_TENANT_OPERATOR_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "tenant-operator.fullname" . }}
                  key: keycloak-user
            - name: KEYCLOAK_TENANT_OPERATOR_PSW
              valueFrom:
                secretKeyRef:
                  name: {{ include "tenant-operator.fullname" . }}
                  key: keycloak-pass
            - name: NEXTCLOUD_TENANT_OPERATOR_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "tenant-operator.fullname" . }}
                  key: nextcloud-user
            - name: NEXTCLOUD_TENANT_OPERATOR_PSW
              valueFrom:
                secretKeyRef:
                  name: {{ include "tenant-operator.fullname" . }}
                  key: nextcloud-pass
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- include "tenant-operator.selectorLabels" . | nindent 18 }}
              topologyKey: kubernetes.io/hostname
