apiVersion: v2
name: crownlabs
description: A Helm chart for CrownLabs

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.4

icon: https://crownlabs.polito.it/images/logo.svg

dependencies:
- name: frontend-app
  version: "0.1.0"
  repository: file://../../frontend/deploy/frontend-app
  condition: frontend-app.enabled

- name: qlkube
  version: "0.1.0"
  repository: file://../../qlkube/deploy/qlkube
  condition: qlkube.enabled

- name: operator
  version: "0.1.0"
  repository: file://../../operators/deploy/operator
  condition: operator.enabled

- name: instance-operator
  version: "0.1.1"
  repository: file://../../operators/deploy/instance-operator
  condition: instance-operator.enabled

- name: bastion-operator
  version: "0.1.1"
  repository: file://../../operators/deploy/bastion-operator
  condition: bastion-operator.enabled

- name: image-list
  version: "0.1.0"
  repository: file://../../operators/deploy/image-list
  condition: image-list.enabled

- name: delete-stale-instances
  version: "0.1.0"
  repository: file://../../operators/deploy/delete-stale-instances
  condition: delete-stale-instances.enabled

- name: exam-agent
  version: "0.1.0"
  repository: file://../../operators/deploy/exam-agent
  condition: exam-agent.enabled

- name: instmetrics
  version: "0.1.0"
  repository: file://../../operators/deploy/instmetrics
  condition: instmetrics.enabled

- name: policies
  version: "0.1.0"
  repository: file://../../policies
  condition: policies.enabled
