apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbacResourcesName }}
  labels: {{- include "qlkube.labels" . | nindent 4 }}
rules:
  {{- range .Values.configuration.subscriptions.apis }}
  - apiGroups:
      - {{ .group }}
    resources:
    {{- range .resources }}
      - {{ .resource }}
      - {{ .resource }}/status
    {{- end }}
    verbs:
      - get
      - list
      - watch
  {{- end }}
