apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qlkube.fullname" . }}
  labels:
    {{- include "qlkube.labels" . | nindent 4 }}
data:
  {{ .Values.configuration.exposedAPIs.fileName }}: |
    const apiGroups = {
      paths: [
        {{- range .Values.configuration.exposedAPIs.apis }}
          {{ quote . }},
        {{- end }}
      ],
    };

    module.exports = { apiGroups };

  {{ .Values.configuration.subscriptions.fileName }}: |
    const subscriptions = [
      {{- range $api := .Values.configuration.subscriptions.apis }}
      {{- range .resources }}
      {
        api: 'apis',
        group: {{ quote $api.group }},
        version: {{ quote .version }},
        resource: {{ quote .resource }},
        type: {{ quote .mapping }},
        {{- if .listMapping }}
        listMapping: {{ quote .listMapping }},
        {{- end }}
      },
      {{- end }}
      {{- end }}
    ];

    module.exports = { subscriptions };

  {{ .Values.configuration.wrappers.fileName }}: |
    const wrappers = [
      {{- range .Values.configuration.wrappers.resources }}
      {
        type: {{ quote .type }},
        fieldWrapper: {{ quote .fieldWrapper }},
        nameWrapper: {{ quote .nameWrapper }},
        queryFieldsRequired: {{ toJson .queryFieldsRequired }},
        parents: {{ toJson  .parents }},
      },
      {{- end }}
    ];

    module.exports = { wrappers };
