name: Check linting
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  golang-lint:
    name: Lint golang files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false

      - name: Check linting
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.34
          working-directory: operators
          args: --timeout=600s


  python-lint:
    name: Lint python files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false

      - name: Check linting
        uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          failIf: any
        env:
          LINTLY_PR: ${{ github.event.pull_request.number }}
          LINTLY_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}


  markdown-lint:
    name: Lint markdown files (check links validity)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false

      - name: Check the validity of the links in the documentation
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'


  shell-lint:
    name: Lint shell files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false

      - name: Run shellcheck
        uses: azohra/shell-linter@v0.4.0
